language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: RrBqX5skNyCLRJ/dEdxjEvZPqN8VHyOXYnUAOApsmCGGieT0vhrCc3E5D5ZjCb0+gQKOSLsjW4oUBN44PJVXA4JM4MCDB4rMnQT5Zp4Rq9/qBt5tqbOtLuy1u0Eg7x0qOxezphqS+E5xKi+gbnnyxwdXd2vG5QNorP1khpBO+Jj+Ly/xSY8ICAmNAbhj0wikQQXRK2JiumjjN0iSwUaEViNDPW7HDNIlOmsYiFJQuguStoTqVULs1EtQW9AEJ8L2LJ54Ou+W3ZZim/bq2jGpsMLDUhxIKdox6FaIoGT4qIMsS+sxCj8234GZE31wDEvjiokUcGlly+o1EfzvpGOazusM+jGzfe1DBNBd+hXPkgdOWKCBzWghW7KxygL/QQUYBLILf5nHM2zmEH39XdNin0Cx0C/POOIp5FEKc/N0QBu5cGznP7mHOrSRGdx/EoL4OaJKxNIuPljAw3xD9jDkxUiepSs4TEgogH4ilEN+FdbnG+3kx1kswb+BsaNNkQe8mayGw3YrwY12Z/mRsRL0Lz0row7aKPg4T5XW6zmY0njHBGAfKthUMKvErgnGI9z/dh0fdaQEZ7r1+Noz7KeVuMK66D80t2KDAkanO1I1S38MUAoEhIZEnP15zYb/Yv+JQBgCdA6JyCLpMBqrcP/WOFMpAOoWhDrnvDenr/i4BA0=
  app: travis-ci
  on:
    repo: MikeyB2/travis-ci
