language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Xx3THA/On3TmPjS9ndjPlGtTUrXyeGxoUfwItNo2QBNecCMrJFzzyg4lA0DuN1QJpXaHSagKXDun1XC17RNRUcahDUu1TEmo85clRMyh4y1CP7glK2yGA0gCvR7kkFcX8OXsF8F4RYa8u/VPxOHEzH1XCEux9Dk25KT6/NyNXD8AZAbcvmyJd5SlFsKsCqYnsWyCQtjyJVAfEGGEFMMGjHNxVhDC3zjre2lIhqBSrDs8oCc1Cw8SSCoTp5jm7gBCBQZktZ0sXVPifQMvtzalukQ/w/23DOtcsuKb0q5hFXrCTsIa6nDZotMjmusgfMqhpe6BOwcl/ZpJ+cecUcPxnohqtEISb0GAX+EzPZazmN8wrLtT6YJj6kgD9XMqfPbjC8yzbzXEFt2uZbEYoJe6Nb4wcsp0QBPq6kW1zTPJK4b3GGFbjCm2ult4um6Zl0h/8Zl/6ivpVkm8XOUMz6AmoeUBZUqQEDESXArEfPRZhSNJ3fAK4u+rpHxRW/vXOEXj6Oy+mO23iMH2bHN5Z+PL8VrUDAyOVjTU9N908eUtsxkjui8Tyu2BjTlkon1ItHiwb7o99SWRjHBOX6DYdkrd2ryLlOVd0n+li+HjR5BBopkow7Fap+Uok+i3SbcBMybqbi0ncsNDcngoy5wO5cL6izGFcNbWZyU8cgPGLqlb/us=
  app: https://quiet-spire-84489.herokuapp.com/
  on:
    repo: MikeyB2/travis-ci
